#ifndef _PSYNC_SETTINGS_H
#define _PSYNC_SETTINGS_H

#define PSYNC_SOCK_CONNECT_TIMEOUT 15
#define PSYNC_SOCK_READ_TIMEOUT    30
#define PSYNC_SOCK_WRITE_TIMEOUT   120

#define PSYNC_STACK_SIZE 64*1024

#define PSYNC_DEFAULT_POSIX_DBNAME ".pcloudsyncdb"

#endif
