Document: pcloudcc
Title: Debian pcloudcc Manual
Author: <insert document author here>
Abstract: This manual describes what pcloudcc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pcloudcc/pcloudcc.sgml.gz

Format: postscript
Files: /usr/share/doc/pcloudcc/pcloudcc.ps.gz

Format: text
Files: /usr/share/doc/pcloudcc/pcloudcc.text.gz

Format: HTML
Index: /usr/share/doc/pcloudcc/html/index.html
Files: /usr/share/doc/pcloudcc/html/*.html
