// OverlayIcon.idl : IDL source for OverlayIcon
//

// This file will be processed by the MIDL tool to
// produce the type library (OverlayIcon.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(7BCA6879-A9F8-47DE-AE05-F5CE7EA3A474),
	dual,
	nonextensible,
	helpstring("IMyOverlayIcon Interface"),
	pointer_default(unique)
]
interface IMyOverlayIcon : IDispatch{
};
[
	uuid(ADF1FA2A-6EAA-4A97-A55F-3C8B92843EF5),
	version(1.0),
	helpstring("OverlayIcon 1.0 Type Library")
]
library OverlayIconLib
{
	importlib("stdole2.tlb");
	[
    uuid(8D0C0582-552A-4A6B-9455-DA63E1F329C0),
    helpstring("pCloudINSYNC Class")
		//uuid(81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40),
	//	helpstring("MyOverlayIcon Class")
	]
	coclass MyOverlayIcon
	{
		[default] interface IMyOverlayIcon;
	};

  [
    uuid(3858ED1B-8F1C-42ED-A8A9-FDBF591E3C6B),
    helpstring("pCloudNOSYNC Class")
    //uuid(81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40),
    //	helpstring("MyOverlayIcon Class")
  ]
  coclass pCloudNoSync
  {
    [default] interface IMyOverlayIcon;
  };

  [
    uuid(D8BFAFBD-B670-4252-9C17-9CF1C64C2BAF),
    helpstring("pCloudINPROGRESS Class")
    //uuid(81539FE6-33C7-4CE7-90C7-1C7B8F2F2D40),
    //	helpstring("MyOverlayIcon Class")
  ]
  coclass pCloudInProgress
  {
    [default] interface IMyOverlayIcon;
  };

}; 
